#!/bin/bash
#
# Romve lines from file which contains a string.
#
#  Usage: removeLinesContainString filename string
#
# @author Jian (Robin) ZHAO 
#
# @email boborabit@gmail.com

string=$2
file=$1
sed -i "/${string}/d" ${file}
