#!/bin/bash
#
# Replace a string by another in all files of current directory recursively.
#
# Author: Jian (Robin) ZHAO 
#
# Email: boborabit@gmail.com


[ $# -eq 3 ] && echo "replacing $1 to $2" || echo "Need exactly two arguments!"

find . -type f -exec sed -i "s/$1/$2/g" {} \;

echo "Done!"


#grep -lR $1 * | xargs sed -i "s/$1/$2/g"

#grep -lR $1 * | xargs replace $1 $2 --

