#!/bin/bash

# change to 163 source
# http://imcn.me/html/y2012/12474.html

# vagrant
# http://www.vagrantbox.es/
# http://blog.csdn.net/samxx8/article/details/38943395

cd ~

sudo apt-get install -y aptitude

# Software and updates > Other Software > Canonical Partners
#sudo aptitude install skype

sudo aptitude install -y vim dos2unix
sudo aptitude install -y imagemagick 
# sudo aptitude install -y terminator kcachegrind
sudo aptitude install -y git git-svn
sudo aptitude install -y mysql-server
#sudo aptitude install  mysql-workbench
sudo aptitude install -y curl ruby

# php
sudo aptitude install -y php5 php5-dev php5-xdebug php5-memcached php5-curl php5-mcrypt php5-gd php5-intl
sudo aptitude install -y phpunit php-codesniffer drush

# composer
if [ "" = "$(which composer)" ]; then
  curl -sS https://getcomposer.org/installer | sudo php
  sudo mv composer.phar /usr/local/bin/
  sudo ln -s /usr/local/bin/composer.phar /usr/local/bin/composer
fi

# install npm
sudo aptitude install -y npm
[ "" = "$(which grunt)" ] && sudo npm install -g grunt-cli bower

# sudo aptitude install -y adobe-flashplugin python-pip
sudo aptitude install -y python-pip
sudo aptitude install -y openjdk-7-jre
# sudo aptitude install ibus-pinyin

# apache2
if [ "" = "$(which apache2)" ]; then
  sudo aptitude install -y apache2
  sudo a2enmod rewrite
  sudo a2enmod macro
  sudo service apache2 restart
fi 

[ ! -d ~/github ] && mkdir ~/github
cd github
[ ! -d ./dircolors-solarized ] && git clone git@github.com:seebi/dircolors-solarized.git
[ ! -f ~/.dircolors ] && ln -s ~/github/dircolors-solarized/dircolors.256dark ~/.dircolors

[ ! -d ./rzBash ] && git clone git@github.com:robin-zhao/rzBash.git
[ ! -f ~/.bash_aliases ] && ln -s ~/github/rzBash/myConfig/bash_aliases ~/.bash_aliases

cd ~

# Nutstore
#if [ "" = "$(which nautilus)" ]; then
#  wget https://jianguoyun.com/static/exe/installer/ubuntu/nautilus_nutstore_amd64.deb
#  sudo dpkg -i ~/nautilus_nutstore_amd64.deb
#fi
# Login and then do:
# ln -s Nutstore/Documents Documents
# ln -s Nutstore/bin bin && chmod 755 bin/*

# Goagent
# sudo ./recompile_python

# memcached
sudo aptitude install -y libmemcached-dev
# NOTE: dont need sasl support 
# http://stackoverflow.com/a/24892703
# http://stackoverflow.com/questions/24407095/error-when-installing-pecl-memcached

# ctags
# http://ctags.sourceforge.net/

# A Screen recorder / Mac OS can go with quicktime.
# http://www.maartenbaert.be/simplescreenrecorder/#what-is-simplescreenrecorder

# Chinese input
# sudo im-config 

# diffmerge http://www.sourcegear.com/diffmerge/downloaded.php
#if [ "" = "$(which diffmerge)" ]; then
#  wget http://download-us.sourcegear.com/DiffMerge/4.2.0/diffmerge_4.2.0.697.stable_amd64.deb
#  sudo dpkg -i ~/diffmerge_4.2.0.697.stable_amd64.deb
#fi

# Setup git mergetool to diffmerge.
# git config --global merge.tool "diffmerge"
# git config --global user.mail "boborabit@qq.com"
# git config --global user.name Jian Zhao"

# Configure drupal & psr2 git submit hook.
# Drupal Coding Standard comes from coder module.
# sudo ln -s /home/robin/www/pharosui.robin/sites/all/modules/contributed/coder/coder_sniffer/Drupal /usr/share/php/PHP/CodeSniffer/Standards/Drupal
# git clone http://git.drupal.org/sandbox/bevan.wishart/1441638.git git_pre_commit_hooks
# copy the pre-commit_* files into your projects .git/hooks/ directory.
#
# do similar for PSR2 : /usr/share/php/PHP/CodeSniffer/Standards/PSR2


# after install ruby
sudo gem install rake
sudo gem install bundler

# https://netbeans.org/downloads/start.html?platform=linux&lang=en&option=php

# sudo ln -s ~/github/rzBash/myConfig/sites-available /etc/apache2/sites-available

# php solr
sudo aptitude install -y make libcurl4-gnutls-dev libxml2-dev libpcre3-dev
if [ ! -f /usr/lib/php5/20121212/solr.so ]; then
  sudo pecl install -f solr-2.0.0
fi

# GeoIp
# http://dev.maxmind.com/geoip/legacy/geolite/
