#!/bin/bash

cd ~

sudo apt-get install -y aptitude

# Software and updates > Other Software > Canonical Partners
sudo aptitude install skype

sudo aptitude install -y vim dos2unix
sudo aptitude install -y imagemagick terminator kcachegrind
sudo aptitude install -y git git-svn
sudo aptitude install -y mysql-server mysql-workbench
sudo aptitude install -y curl

# php
sudo aptitude install -y php5 php5-dev php5-xdebug php5-memcached php5-curl php5-mcrypt php5-gd
sudo aptitude install -y phpunit php-codesniffer drush

# php solr
sudo aptitude install -y libcurl4-gnutls-dev libxml2-dev libpcre3-dev

if [ ! -f /usr/lib/php5/20121212/solr.so ]; then
  sudo pecl install -f solr-2.0.0
fi

# composer
if [ "" = "$(which composer)" ]; then
  curl -sS https://getcomposer.org/installer | sudo php
  sudo mv composer.phar /usr/local/bin/
  sudo ln -s /usr/local/bin/composer.phar /usr/local/bin/composer
fi

# install npm
sudo aptitude install -y npm
[ "" = "$(which grunt)" ] && sudo npm install -g grunt-cli bower

sudo aptitude install -y adobe-flashplugin python-pip
sudo aptitude install -y openjdk-7-jre
sudo aptitude install ibus-pinyin

# apache2
if [ "" = "$(which apache2)" ]; then
  sudo aptitude install -y apache2
  sudo a2enmod rewrite
  sudo a2enmod macro
  sudo service apache2 restart
fi 

[ ! -d ~/github ] && mkdir ~/github
cd github
[ ! -d ./dircolors-solarized ] && git clone git@github.com:seebi/dircolors-solarized.git
[ ! -f ~/.dircolors ] && ln -s ~/github/dircolors-solarized/dircolors.256dark ~/.dircolors

[ ! -d ./rzBash ] && git clone git@github.com:robin-zhao/rzBash.git
[ ! -f ~/.bash_aliases ] && ln -s ~/github/rzBash/myConfig/bash_aliases ~/.bash_aliases

cd ~

# nutstore
if [ ! -f ~/nautilus_nutstore_amd64.deb ]; then
  wget https://jianguoyun.com/static/exe/installer/ubuntu/nautilus_nutstore_amd64.deb
  sudo dpkg -i ~/nautilus_nutstore_amd64.deb
fi
# Login and then do:
# ln -s Nutstore/Documents Documents
# ln -s Nutstore/bin bin && chmod 755 bin/*

# goagent
# sudo ./recompile_python

# memcached
sudo aptitude install -y libmemcached-dev
# http://stackoverflow.com/questions/24407095/error-when-installing-pecl-memcached

# ctags
# http://ctags.sourceforge.net/

# screen recorder 
# http://www.maartenbaert.be/simplescreenrecorder/#what-is-simplescreenrecorder

# chinese input
# sudo im-config 

# diffmerge http://www.sourcegear.com/diffmerge/downloaded.php
if [ "" = "$(which diffmerge)" ]; then
  wget http://download-us.sourcegear.com/DiffMerge/4.2.0/diffmerge_4.2.0.697.stable_amd64.deb
  sudo dpkg -i ~/diffmerge_4.2.0.697.stable_amd64.deb
fi

# https://netbeans.org/downloads/start.html?platform=linux&lang=en&option=php
