#!/bin/bash
#
# Contains common functions. 
#
# @author Jian (Robin) ZHAO 
#
# @email boborabit@gmail.com


#
# Find regex keyword and return the occurance lines.
#
#  @param regex     The Regular Expression.
#  @param file  The filename.
#
function getKeywordLines()
{
  local regex=$1
  local file=$2
  local lines=$(grep -n -E "${regex}" ${file} | cut -d: -f1 | sort -nr);
  for i in ${lines};do
    echo $i;
  done;
}

#
# Append a line into a file.
#
# @file      The filename.
# @line      The line to append string.
# @string    The string to append.
# @numSpaces Number of preceeding spaces.
#
function appendLine()
{
  local file=$1
  local line=$2
  local string=$3
  local numSpaces=$4
  space="";
  if [ ${numSpaces} -gt 1 ]; then
    space="$(printf ' %0.s' $(seq 1 ${numSpaces}))";
  fi
  local regex=${line}'a\'${space}${string};
  sed -i "${regex}" ${file} 
}

#
# Get Position of first non-space character of a line.
#
# @file The filename.
# @line The line number.
#
function intentPosition()
{
  local file=$1
  local line=$2
  
  local string=$(cat ${file} | head -${line} | tail -1 | sed -r 's/^(\s*)([^\s].*$)/\1/g');
  echo $(expr length "${string}");
}

export -f getKeywordLines
export -f appendLine
export -f intentPosition
