#!/bin/bash
#
# prepend file doc.
#
# @author Jian (Robin) ZHAO 
#
# @email boborabit@gmail.com

filename=$1

function prependFileDoc()
{
  cat $1 | head -5 | grep '/\*\*' > /dev/null

  if [ $? -eq 0 ]; then
    return 1;
  fi

  sed -i '1a\/**' $1
  sed -i '2a\ * @file' $1
  sed -i '3a\ * Description of filename.' $1
  sed -i '4a\ */' $1
  sed -i '5a\' $1
}

function prependDocToLine()
{
  local file=$1
  local line=$2
  local numSpaces=$3

  cat ${file} | head -${line} | tail -5 | grep '\*' > /dev/null
  if [ $? -eq 0 ]; then
    return 1;
  fi

  appendLine ${file} "$(( ${line} - 1 ))" '/**' ${numSpaces} 
  appendLine ${file} "$(( ${line} - 0 ))" ' * Description of function.' ${numSpaces} 
  appendLine ${file} "$(( ${line} + 1 ))" ' */' ${numSpaces} 
}

function prependFunctionDoc()
{
  local lines=$(grep -n -E "^function [a-zA-Z_]+" $1 | cut -d: -f1 | sort -nr);

  for i in ${lines}; do
    prependDocToLine $1 ${i} 0; 
  done
}

function prependMethodDoc()
{
  local lines=$(grep -n -E "^\s+(public|private|protected)(\sstatic)?\s[a-zA-Z_]+" $1 | cut -d: -f1 | sort -nr);

  # @todo find num of spaces.
  local numSpace=4;

  for i in ${lines}; do
    prependDocToLine $1 ${i} ${numSpace}; 
  done
}

prependFileDoc ${filename};
prependFunctionDoc ${filename};
prependMethodDoc ${filename};
