#!/bin/bash
#
# Format concat operator.
#
# Author: Jian (Robin) ZHAO 
#
# Email: boborabit@gmail.com

filename=$1


sed -i -r 's/("[^"\)]*?")\s*\.\s*([^\n])/\1 . \2/g' ${filename}
sed -i -r "s/('[^'\)]*?')\s*\.\s*([^\n])/\1 . \2/g" ${filename}
sed -i -r "s/(\$[a-zA-Z_])\s*\.\s*([^\n])/\1 . \2/g" ${filename}
