#!/bin/bash
#
# Format comment.
#
# @author Jian (Robin) ZHAO 
#
# @email boborabit@gmail.com

filename=$1

sed -i -r 's/([^:]\/\/)\s?([a-zA-Z])/\1 \U\2/g' ${filename}

sed -i -r 's/([^:]\/\/.*[^\?\.\;])$/\1./g' ${filename}

