#!/bin/bash
#
# prepend file doc.
#
# @author Jian (Robin) ZHAO 
#
# @email boborabit@gmail.com

filename=$1

function prependFileDoc()
{
  sed -i '1a\/**' $1
  sed -i '2a\ * @file' $1
  sed -i '3a\ * Description of filename.' $1
  sed -i '4a\ */' $1
  sed -i '5a\' $1
}

cat ${filename} | head -5 | grep '/\*\*' > /dev/null

if [ $? -eq 1 ]; then
  prependFileDoc ${filename};
fi

